Repository Itz-snj/React-Beginner, pull requests merged in 2025-03, with the labels that each got.

#7 Solved #1 issue
  package-lock.json
  package.json
  src/App.jsx
  src/assests/Frame 20.png
  src/assests/Illustration.png
  src/assests/c1.png
  src/assests/c2.png
  src/assests/c3.png
  src/assests/c4.png
  src/assests/c5.png
  src/assests/c6.png
  src/assests/home.png
  src/assests/tokyo-browser-window-with-emoticon-likes-and-stars-around 2.png
  src/assests/tokyo-magnifier-web-search-with-elements 2.png
  src/assests/tokyo-many-browser-windows-with-different-information 2.png
  src/assests/tokyo-selecting-a-value-in-the-browser-window 2.png
  src/assests/tokyo-sending-messages-from-one-place-to-another 2.png
  src/assests/tokyo-volumetric-analytics-of-different-types-in-web-browsers 2.png
  src/assets/react.svg
  src/components/home.jsx
  src/components/navbar.jsx
  src/index.css
Labels: apertre2.0, medium

#9 Solved issue #8
  package-lock.json
  package.json
  src/App.jsx
  src/assests/s1.png
  src/assests/s2.png
  src/assests/s3.png
  src/assests/s4.png
  src/assests/s5.png
  src/assests/s6.png
  src/components/services.jsx
Labels: apertre2.0, medium

#13 Solved #10
  src/App.jsx
  src/assests/news.png
  src/components/case.jsx
Labels: apertre2.0, easy

#12 Added "Our Working Process" Section and Update Font to Space Grotesk
  index.html
  src/App.jsx
  src/components/WorkingProcess.jsx
  src/index.css
Labels: apertre2.0, easy

#17 Footer
  .gitignore
  package-lock.json
  src/App.jsx
  src/assests/logow.png
  src/components/WorkingProcess.jsx
  src/components/footer.jsx
  src/index.css
Labels: apertre2.0, frontend, easy

#16 Issue #15 solved
  package-lock.json
  package.json
  src/components/case.jsx
  src/components/home.jsx
  src/components/navbar.jsx
  src/components/services.jsx
Labels: apertre2.0, frontend, easy, responsiveness

#20 Solved #18
  package-lock.json
  package.json
  src/App.jsx
  src/components/navbar.jsx
  src/components/team.jsx
Labels: apertre2.0, medium
